### ISSUE TITLE
Regex

### ISSUE THREAD

**Issue by calanzer** [skothawala/MessageParser#2]
I had trouble understanding how you used Regex, It defiantly works but you could maybe use some more documentation explaining how it works and how you used it.

**Comment by skothawala** [comment]
The regex isn't mine. It was actually written by the Android team at google. The code I'm using is from the actual Android source code. I mentioned so in the comment on [TextUtils.js:31](https://github.com/skothawala/MessageParser/blob/master/TextUtils.js#L31)

Thanks
