### ISSUE TITLE
Check to make sure the first character of a topic is a letter.

### ISSUE THREAD

**Issue by spkuehl** [skothawala/MessageParser#4]
Twitter requires a topic to be a hash symbol followed by a letter, then followed letters, numbers, or underscores. This could be tested and if needed a special case could be added to your program to filter out invalid topics.

'#1_is_not_a_topic' is not a topic
'#this_1_is_a_topic' is a topic

**Comment by skothawala** [comment]
Thanks. I've fixed the issue now.
