### ISSUE TITLE
Mentions issue

### ISSUE THREAD

**Issue by the872** [skothawala/MessageParser#5]
First off, I applaud your work with making this as robust as it is. However while testing some cases, I did find that your code did not pick up the mentions that had punctuation that directly followed. Examples that I got off Twitter:
- .@blessedbwander Might? No, you _will_ meet a Blackhawk tomorrow @simply_shelb!
- Some of the XXL staff tried to guess @kanyewest's new album title. #TLOP 

The other thing with the mentions, which isn't too big of a deal in terms of functionality was that if there was punctuation in front of a mention, it would include it in the output (see first example above). 

Other than that, looks good!

**Comment by skothawala** [comment]
Thanks for pointing this out. I've fixed the issue and in the process ended up redoing a lot of the backend.

Thanks
