### ISSUE TITLE
Small Issue with Mention and Topic Regex

### ISSUE THREAD

**Issue by chernandez7** [skothawala/MessageParser#6]
It's not a big problem and this is for an extreme case that will probably never happen but when analyzing a tweet like:

`##topictest @@mentiontest`
- There is no topic found.
- Mention is listed as: `@@mentiontest`

I'm not sure if this is a bug in the code or an intended feature, but just wanted this to be known.
The way that twitter itself would have handled these is by assigning the topic: `#topictest` and the mention: `@mentiontest`. So it seems to ignore all but the last special character if the same one is used multiple times.

**Comment by skothawala** [comment]
Thanks for this. I've redone a lot of the backend workings and this should be fixed.
