### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by FrancisDelaPena** [skothawala/MessageParser#9]
Personally, for now what I'd really suggest is providing some detailed comments in your code.  Other than that, I can't find many other issues off the bat.

**Comment by skothawala** [comment]
I think that I have more than enough comments. However, that is obviously biased considering I wrote the code.

Can you be more specific?

**Comment by FrancisDelaPena** [comment]
I was looking at the TextUtilsTest code specifically.  I took another look.  I'm not overly familiar with JavaScript, so I barely noticed the "describe" parts.  _Now_ I understand what that is.  I'm not sure if that was just my own ignorance, or if it should be made clear in a comment anyway.

Apologies for any misunderstanding.
